### PR TITLE
Disabled the secret question field (fixes #36) 

### LINKED ISSUE #36: Make Security Questions Uneditable
Can we make the security questions uneditable, as there's no point of keeping them editable? Also one can just use Tab to answer the next questions.

### PR DESCRIPTION
**Pull request by ooyeraju**
Fixes #36 by @ooyeraju 

### Description 
Made the secret question field uneditable. as discussed in PR. 

### Screenshot 
Screenshot from 2020-09-22 12-22-23

PS: Thanks a lot @sahil-shubham for your Help.

### CODE REVIEW

**Comment by ooyeraju** [comment]
The @thealphadollar , me and @sahil-shubham discussed that we should mention that _One needs to disable the existing ERP Extension in his/her browser before running this locally_ in the CONTRIBUTING.md file. 
As both of us faced this issue when we tried to run it locally. And it's kinda frustrating for any newcomer.

**Review by thealphadollar — APPROVED** [review]
This looks simple and very useful to me. Thanks Rajnish. 

@sahil-shubham @rakaar Can you please review once as well?

**Comment by thealphadollar** [comment]
> The @thealphadollar , me and @sahil-shubham discussed that we should mention that _One needs to disable the existing ERP Extension in his/her browser before running this locally_ in the CONTRIBUTING.md file. 
> As both of us faced this issue when we tried to run it locally. And it's kinda frustrating for any newcomer. 

Yes. This is a keen finding. Would you like to raise a *separate* pull request for this?

**Review by sahil-shubham — APPROVED** [review]
Looks good to me. Thanks for finding and fixing this issue @ooyeraju.

**Comment by ooyeraju** [comment]
> > The @thealphadollar , me and @sahil-shubham discussed that we should mention that _One needs to disable the existing ERP Extension in his/her browser before running this locally_ in the CONTRIBUTING.md file.
> > As both of us faced this issue when we tried to run it locally. And it's kinda frustrating for any newcomer.
> 
> Yes. This is a keen finding. Would you like to raise a _separate_ pull request for this?

Yea, Sure. I'll do it.

**Pull request merged**
