### PR TITLE
fixes #33

### LINKED ISSUE #33: unexpected behaviour of the credential saved message
The issue is with the message **"Your credentials have been saved"**.

### Expected Behaviour 
The message should show up only after entering all the details. 

### Current Behaviour
The message pops up after every keypress.

### Screenshots
Screenshot from 2020-09-14 01-46-17

### PR DESCRIPTION
**Pull request by sahil-shubham**
Now the extension just shows `Your credentials have been saved` before all the credentials have been entered. After which it also shows the link to the erp with the message.

This fixes #33

### CODE REVIEW

**Comment by sahil-shubham** [comment]
Sorry I didn't include the new firefox changes in this branch, would be creating a branch with the both the changes included.

**Comment by thealphadollar** [comment]
@sahil-shubham It's actually a good practice to open a single PR per feature or issue you solve. It helps the reviewers to review quickly and independently. Do you think we should open this PR and keep firefox changes separate?

**Comment by sahil-shubham** [comment]
> Do you think we should open this PR and keep firefox changes separate?

It may create some merge issues later on. Plus, this is an issue we want fixed in the extension on both chrome and firefox, so I thought it would for the best.

**Comment by thealphadollar** [comment]
> It may create some merge issues later on.

We will solve them together, no issues :D

> this is an issue we want fixed in the extension on both chrome and firefox, so I thought it would for the best.

Oh! That sounds cool. If you feel  it suits better there, I will go with your feeling <3

**Pull request closed without merging**
