### PR TITLE
added reset confirmation warning;

### PR DESCRIPTION
**Pull request by sahil-shubham**
## Changes
- added reset confirmation dialog box

## Screenshots
warning

### CODE REVIEW

**Comment by sahil-shubham** [comment]
@thealphadollar I found this kind of reset confirmation to be the best alternative. Let me know if I need to make any changes in the warning message.

I wanted to make this PR in the night itself, but I noticed a bug in which if I close the extension while this confirmation window is open, the extension becomes unclickable. I tried to figure this out on my own, but couldn't. It would be great if you could help me with figuring why this is happening.

**Comment by thealphadollar** [comment]
@sahil-shubham While I was not able to figure out the issue - I've created the issue #50. Please have a look at it and see if we should add any more details.

I've not invested much time since the extension still works and logs in - only interaction is missing. Also, I believe this would be a very rare case to invest time in right now and delay the release (v2.0 has been released on Firefox and Chrome will be done shortly by @athityakumar ).

**Review by thealphadollar — COMMENTED** [review]
LGTM. Thank you for working on the fix Sahil.

**Comment by sahil-shubham** [comment]
@thealphadollar I agree with you, merging this and making an issue for the same was a better solution. I don't think a normal user would be able to replicate this bug very often, but I would still try to look into this again. Thank you for letting me know your thought process.

**Pull request merged**
