### PR TITLE
[BUGFIX] Add jQuery Script To Background

### LINKED ISSUE #15: Installing on windows leads to `Uncaught ReferenceError: $ is not defined`
Find attached screenshot

I've ran into this error on Chrome 70.0, Windows 10. Could installing something fix this issue?
Is this a windows specific issue or a laptop specific issue? Could be verified by others by installing this on windows.

image

### PR DESCRIPTION
**Pull request by thealphadollar**
fixes #15 

The jQuery script wasn't loaded in the background. I wonder how has it been working all the time.

https://stackoverflow.com/questions/19199956/chrome-extension-is-not-defined-error

@kaustubhhiware Please check, I couldn't test it (no windows 10 with Chrome 70).

### CODE REVIEW

**Comment by kaustubhhiware** [comment]
I'll check this and let you know by tomorrow (have some work to do in Linux).

PS: sending PR's via master ?

**Comment by thealphadollar** [comment]
Oh! It was a quick hack and I forgot to make a new branch.

**Comment by kaustubhhiware** [comment]
Although the extension seems to work now, there are still some issues that need to be resolved in Windows. Seems like we need to make those developmental changes via Windows only.

Note: Did not run into any errors on linux system.

image

**Comment by thealphadollar** [comment]
@kaustubhhiware Oh, it is due to a recent change in the Chrome that has embedded CSP.

I've added the respective tags for it to work perfectly now. Please test it :)

**Comment by kaustubhhiware** [comment]
Adding the csrf line broke the initial popup screen where users are supposed to enter their roll number, password and security answers.

**Pull request merged**
