### PR TITLE
Remove Deprecated 'applications' Entry from Manifest

### LINKED ISSUE #34: Release Firefox Extension In Firefox Store
Once issue #3 is fixed, we should publish the extension in the firefox add ons store.

AFAIK, we will use the MetaKGP account on the firefox store for the same.

### PR DESCRIPTION
**Pull request by thealphadollar**
This PR brings changes that solve the error encountered while submitting the addon in the firefox store, as follows.

## The Bug / Issue

image

If we aim to rectify this with a unique ID, the manifest.json will become incompatible with Chrome (I'm assuming) and hence we will have to maintain/update manifest.json before generating packages. 

## Reason

The error/issue was caused by the following entry in `manifest.json`.

```JSON
"applications":{	
	"gecko" :{	
		"id" : "erp_auto_login@metakgp.com"	
	}	
}
```

## Solution

I've removed the `applications` entry from manifest.json [1] and generated a new firefox package file. 

## Potential Challenges

@athityakumar Please help me understand, with your experience of submitting extension in the chrome store, is the "applications" key important? I did some trivial internet search and came to find that it is not required[2]. I want to be sure of the same with your review and opinion.

UPDATE: As informed by @sahil-shubham , he added it for manual installation and we will not require it if we publish from the firefox store. 

## References

- [1] https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings
- [2] https://stackoverflow.com/questions/37127330/unrecognized-manifest-key-applications-warning-for-google-chrome

## Related Issues

closes #34

### CODE REVIEW

**Review by sahil-shubham — APPROVED** [review]
I added a made up id as I wasn't able to make the extension work properly while loading the extension temporarily. Few API's don't work [without an id or with a temporary id](https://extensionworkshop.com/documentation/develop/extensions-and-the-add-on-id/#When_do_you_need_an_add-on_ID), `storage.sync` being one of them which we have used. 

But firefox assigns a permanent id when one tries to publish the extension using their account on mozilla, hence it is okay to remove the gecko id now. This can be confirmed through [this article](https://wiki.mozilla.org/WebExtensions/Applications) , it says `The use of an application id is something we could avoid because everything has to come through AMO to be signed and we could create it for the add-on developer.` The extension would be automatically signed after it passes the validation.

cc/ @athityakumar

**Comment by thealphadollar** [comment]
@sahil-shubham Thanks for bringing it to my notice. So, what we will do it only publish through the Firefox store and once the extension is live on the firefox store, we will merge this PR and remove `.xpi` file from repo as well. Does that sound good?

Thank you for helping me understand the issue.

**Comment by sahil-shubham** [comment]
> Does that sound good?

@thealphadollar Yes, that sounds perfect. Thank you very much for bringing this to my notice, I learned a few more things :grin:   

I would also update the README (removing the intructions for manual installation), unless you would want to do that yourself.

**Comment by thealphadollar** [comment]
> I would also update the README (removing the instructions for manual installation) unless you would want to do that yourself.

Oh! Right. It had almost slipped my mind, though that's what reviews are for. Thanks. 

We will do README update once the firefox addon is live in the addon store.

**Comment by thealphadollar** [comment]
@sahil-shubham @athityakumar Please re-review the updated Pull Request.

**Review by sahil-shubham — APPROVED** [review]
@thealphadollar Looks good to me, thank you very much.

**Pull request merged**
